#!/bin/bash

# creates sym link from simply being in directory of execuable and 
# giving executable:
# Ex: while inside directory where 'racket' executable exists, 
# type command:
# $> symLinkGen racket
# and sym link: /usr/bin/racket will be generated for you.

EXEC_PATH="$(pwd)/$1"

if [ "$1" == "-r" ]; then
    sudo rm /usr/bin/$2
elif [[ ! -z "$1" ]]; then
    sudo ln -s $EXEC_PATH /usr/bin/$1
else
    echo "Useage: $0 [options] executableName"
    echo "options:"
    echo "  -r : remove symlink"
fi
